
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 25 17:05:06 CST 2020
//----------------------------------------------------

package Gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

