
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 28 10:38:11 CST 2020
//----------------------------------------------------

package Gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ERRO = 3;
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

